import type { NewVendor } from "../schema.js";

export const vendorSeedData: NewVendor[] = [
  // Cloud
  {
    name: "AWS",
    slug: "aws",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg",
    category: "Cloud",
    emailPatterns: ["no-reply@marketplace.aws", "aws-billing@amazon.com", "noreply@amazon.com"],
  },
  {
    name: "Google Cloud",
    slug: "gcp",
    logoUrl: "https://www.gstatic.com/devrel-devsite/prod/v1241c04ebcb2127897d6c18571d41b0e0bd58db3eeb1d88c88f435e48756bca2/cloud/images/favicons/onecloud/super_cloud.png",
    category: "Cloud",
    emailPatterns: ["billing-noreply@google.com", "cloud-noreply@google.com"],
  },
  {
    name: "Microsoft Azure",
    slug: "azure",
    logoUrl: "https://azure.microsoft.com/favicon.ico",
    category: "Cloud",
    emailPatterns: ["azure-noreply@microsoft.com", "azurebilling@microsoft.com"],
  },
  {
    name: "Vercel",
    slug: "vercel",
    logoUrl: "https://assets.vercel.com/image/upload/v1588805858/repositories/vercel/logo.png",
    category: "Cloud",
    emailPatterns: ["billing@vercel.com", "notifications@vercel.com"],
  },
  {
    name: "Railway",
    slug: "railway",
    logoUrl: "https://railway.app/brand/logo-light.svg",
    category: "Cloud",
    emailPatterns: ["billing@railway.app", "team@railway.app"],
  },
  {
    name: "Render",
    slug: "render",
    logoUrl: "https://render.com/favicon.ico",
    category: "Cloud",
    emailPatterns: ["billing@render.com", "noreply@render.com"],
  },
  {
    name: "DigitalOcean",
    slug: "digitalocean",
    logoUrl: "https://www.digitalocean.com/favicon.ico",
    category: "Cloud",
    emailPatterns: ["billing@digitalocean.com", "noreply@digitalocean.com"],
  },
  {
    name: "Fly.io",
    slug: "fly-io",
    logoUrl: "https://fly.io/favicon.ico",
    category: "Cloud",
    emailPatterns: ["billing@fly.io", "support@fly.io"],
  },
  {
    name: "Netlify",
    slug: "netlify",
    logoUrl: "https://www.netlify.com/favicon.ico",
    category: "Cloud",
    emailPatterns: ["billing@netlify.com", "team@netlify.com"],
  },
  {
    name: "Heroku",
    slug: "heroku",
    logoUrl: "https://www.heroku.com/favicon.ico",
    category: "Cloud",
    emailPatterns: ["billing@heroku.com", "noreply@heroku.com"],
  },

  // CI/CD
  {
    name: "GitHub",
    slug: "github",
    logoUrl: "https://github.githubassets.com/favicons/favicon.svg",
    category: "CI/CD",
    emailPatterns: ["noreply@github.com", "billing@github.com", "support@github.com"],
  },
  {
    name: "GitLab",
    slug: "gitlab",
    logoUrl: "https://about.gitlab.com/ico/favicon.ico",
    category: "CI/CD",
    emailPatterns: ["billing@gitlab.com", "noreply@gitlab.com"],
  },
  {
    name: "CircleCI",
    slug: "circleci",
    logoUrl: "https://circleci.com/favicon.ico",
    category: "CI/CD",
    emailPatterns: ["billing@circleci.com", "noreply@circleci.com"],
  },
  {
    name: "Buildkite",
    slug: "buildkite",
    logoUrl: "https://buildkite.com/favicon.ico",
    category: "CI/CD",
    emailPatterns: ["billing@buildkite.com", "support@buildkite.com"],
  },
  {
    name: "Travis CI",
    slug: "travis-ci",
    logoUrl: "https://www.travis-ci.com/favicon.ico",
    category: "CI/CD",
    emailPatterns: ["billing@travis-ci.com", "noreply@travis-ci.com"],
  },

  // Monitoring
  {
    name: "Datadog",
    slug: "datadog",
    logoUrl: "https://www.datadoghq.com/favicon.ico",
    category: "Monitoring",
    emailPatterns: ["billing@datadoghq.com", "noreply@datadoghq.com"],
  },
  {
    name: "Sentry",
    slug: "sentry",
    logoUrl: "https://sentry.io/favicon.ico",
    category: "Monitoring",
    emailPatterns: ["billing@sentry.io", "noreply@sentry.io"],
  },
  {
    name: "New Relic",
    slug: "new-relic",
    logoUrl: "https://newrelic.com/favicon.ico",
    category: "Monitoring",
    emailPatterns: ["billing@newrelic.com", "noreply@newrelic.com"],
  },
  {
    name: "PagerDuty",
    slug: "pagerduty",
    logoUrl: "https://www.pagerduty.com/favicon.ico",
    category: "Monitoring",
    emailPatterns: ["billing@pagerduty.com", "noreply@pagerduty.com"],
  },
  {
    name: "Honeycomb",
    slug: "honeycomb",
    logoUrl: "https://www.honeycomb.io/favicon.ico",
    category: "Monitoring",
    emailPatterns: ["billing@honeycomb.io", "support@honeycomb.io"],
  },
  {
    name: "LogRocket",
    slug: "logrocket",
    logoUrl: "https://logrocket.com/favicon.ico",
    category: "Monitoring",
    emailPatterns: ["billing@logrocket.com", "noreply@logrocket.com"],
  },

  // AI/ML
  {
    name: "OpenAI",
    slug: "openai",
    logoUrl: "https://openai.com/favicon.ico",
    category: "AI/ML",
    emailPatterns: ["billing@openai.com", "noreply@openai.com", "receipts@openai.com"],
  },
  {
    name: "Anthropic",
    slug: "anthropic",
    logoUrl: "https://www.anthropic.com/favicon.ico",
    category: "AI/ML",
    emailPatterns: ["billing@anthropic.com", "noreply@anthropic.com"],
  },
  {
    name: "Replicate",
    slug: "replicate",
    logoUrl: "https://replicate.com/favicon.ico",
    category: "AI/ML",
    emailPatterns: ["billing@replicate.com", "hello@replicate.com"],
  },
  {
    name: "Hugging Face",
    slug: "huggingface",
    logoUrl: "https://huggingface.co/favicon.ico",
    category: "AI/ML",
    emailPatterns: ["billing@huggingface.co", "noreply@huggingface.co"],
  },
  {
    name: "Pinecone",
    slug: "pinecone",
    logoUrl: "https://www.pinecone.io/favicon.ico",
    category: "AI/ML",
    emailPatterns: ["billing@pinecone.io", "support@pinecone.io"],
  },

  // Databases
  {
    name: "Supabase",
    slug: "supabase",
    logoUrl: "https://supabase.com/favicon.ico",
    category: "Databases",
    emailPatterns: ["billing@supabase.io", "noreply@supabase.io", "billing@supabase.com"],
  },
  {
    name: "PlanetScale",
    slug: "planetscale",
    logoUrl: "https://planetscale.com/favicon.ico",
    category: "Databases",
    emailPatterns: ["billing@planetscale.com", "noreply@planetscale.com"],
  },
  {
    name: "MongoDB Atlas",
    slug: "mongodb-atlas",
    logoUrl: "https://www.mongodb.com/favicon.ico",
    category: "Databases",
    emailPatterns: ["billing@mongodb.com", "noreply@mongodb.com"],
  },
  {
    name: "Redis Cloud",
    slug: "redis-cloud",
    logoUrl: "https://redis.com/favicon.ico",
    category: "Databases",
    emailPatterns: ["billing@redis.com", "noreply@redis.com"],
  },
  {
    name: "Neon",
    slug: "neon",
    logoUrl: "https://neon.tech/favicon.ico",
    category: "Databases",
    emailPatterns: ["billing@neon.tech", "noreply@neon.tech"],
  },
  {
    name: "Upstash",
    slug: "upstash",
    logoUrl: "https://upstash.com/favicon.ico",
    category: "Databases",
    emailPatterns: ["billing@upstash.com", "support@upstash.com"],
  },

  // Productivity
  {
    name: "Slack",
    slug: "slack",
    logoUrl: "https://slack.com/favicon.ico",
    category: "Productivity",
    emailPatterns: ["billing@slack.com", "noreply@slack.com", "feedback@slack.com"],
  },
  {
    name: "Notion",
    slug: "notion",
    logoUrl: "https://www.notion.so/favicon.ico",
    category: "Productivity",
    emailPatterns: ["billing@notion.so", "noreply@notion.so", "team@makenotion.com"],
  },
  {
    name: "Linear",
    slug: "linear",
    logoUrl: "https://linear.app/favicon.ico",
    category: "Productivity",
    emailPatterns: ["billing@linear.app", "noreply@linear.app"],
  },
  {
    name: "Figma",
    slug: "figma",
    logoUrl: "https://www.figma.com/favicon.ico",
    category: "Design",
    emailPatterns: ["billing@figma.com", "noreply@figma.com"],
  },
  {
    name: "Miro",
    slug: "miro",
    logoUrl: "https://miro.com/favicon.ico",
    category: "Productivity",
    emailPatterns: ["billing@miro.com", "noreply@miro.com"],
  },
  {
    name: "Airtable",
    slug: "airtable",
    logoUrl: "https://airtable.com/favicon.ico",
    category: "Productivity",
    emailPatterns: ["billing@airtable.com", "noreply@airtable.com"],
  },
  {
    name: "Loom",
    slug: "loom",
    logoUrl: "https://www.loom.com/favicon.ico",
    category: "Productivity",
    emailPatterns: ["billing@loom.com", "noreply@loom.com"],
  },

  // Dev Tools
  {
    name: "JetBrains",
    slug: "jetbrains",
    logoUrl: "https://www.jetbrains.com/favicon.ico",
    category: "Dev Tools",
    emailPatterns: ["sales@jetbrains.com", "noreply@jetbrains.com"],
  },
  {
    name: "Postman",
    slug: "postman",
    logoUrl: "https://www.postman.com/favicon.ico",
    category: "Dev Tools",
    emailPatterns: ["billing@postman.com", "noreply@postman.com"],
  },
  {
    name: "ngrok",
    slug: "ngrok",
    logoUrl: "https://ngrok.com/favicon.ico",
    category: "Dev Tools",
    emailPatterns: ["billing@ngrok.com", "support@ngrok.com"],
  },
  {
    name: "Replit",
    slug: "replit",
    logoUrl: "https://replit.com/favicon.ico",
    category: "Dev Tools",
    emailPatterns: ["billing@replit.com", "noreply@replit.com"],
  },

  // Auth/Infra
  {
    name: "Auth0",
    slug: "auth0",
    logoUrl: "https://auth0.com/favicon.ico",
    category: "Auth/Infra",
    emailPatterns: ["billing@auth0.com", "noreply@auth0.com"],
  },
  {
    name: "Clerk",
    slug: "clerk",
    logoUrl: "https://clerk.com/favicon.ico",
    category: "Auth/Infra",
    emailPatterns: ["billing@clerk.dev", "noreply@clerk.dev", "billing@clerk.com"],
  },
  {
    name: "Stripe",
    slug: "stripe",
    logoUrl: "https://stripe.com/favicon.ico",
    category: "Auth/Infra",
    emailPatterns: ["receipts@stripe.com", "noreply@stripe.com", "billing@stripe.com"],
  },
  {
    name: "Twilio",
    slug: "twilio",
    logoUrl: "https://www.twilio.com/favicon.ico",
    category: "Auth/Infra",
    emailPatterns: ["billing@twilio.com", "noreply@twilio.com"],
  },
  {
    name: "SendGrid",
    slug: "sendgrid",
    logoUrl: "https://sendgrid.com/favicon.ico",
    category: "Auth/Infra",
    emailPatterns: ["billing@sendgrid.com", "noreply@sendgrid.com"],
  },
  {
    name: "Cloudflare",
    slug: "cloudflare",
    logoUrl: "https://www.cloudflare.com/favicon.ico",
    category: "Auth/Infra",
    emailPatterns: ["billing@cloudflare.com", "noreply@cloudflare.com"],
  },
  {
    name: "Resend",
    slug: "resend",
    logoUrl: "https://resend.com/favicon.ico",
    category: "Auth/Infra",
    emailPatterns: ["billing@resend.com", "noreply@resend.com"],
  },
];
