import type { NewVendor } from "../schema";

export const vendorSeedData: NewVendor[] = [
  // Cloud & Infrastructure
  {
    name: "AWS",
    slug: "aws",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg",
    category: "Cloud",
    emailPatterns: ["@amazon.com", "@aws.amazon.com", "aws-billing@amazon.com", "aws-receivables-support@email.amazon.com"],
  },
  {
    name: "Google Cloud",
    slug: "gcp",
    logoUrl: "https://www.gstatic.com/devrel-devsite/prod/v1241c04ebcb2127897d6c18571d41b0e0bd58db3eeb1d88c88f435e48756bca2/cloud/images/favicons/onecloud/super_cloud.png",
    category: "Cloud",
    emailPatterns: ["billing-noreply@google.com", "cloud-noreply@google.com"],
  },
  {
    name: "Google Workspace",
    slug: "google-workspace",
    logoUrl: "https://www.gstatic.com/images/branding/product/2x/hh_workspace_64dp.png",
    category: "Productivity",
    emailPatterns: [],  // Matched by subject line containing "google workspace" from payments-noreply@google.com
  },
  {
    name: "Microsoft Azure",
    slug: "azure",
    logoUrl: "https://azure.microsoft.com/favicon.ico",
    category: "Cloud",
    emailPatterns: ["@microsoft.com", "@azure.com", "azure-noreply@microsoft.com"],
  },
  {
    name: "Vercel",
    slug: "vercel",
    logoUrl: "https://assets.vercel.com/image/upload/v1588805858/repositories/vercel/logo.png",
    category: "Cloud",
    emailPatterns: ["@vercel.com"],
  },
  {
    name: "Railway",
    slug: "railway",
    logoUrl: "https://railway.app/brand/logo-light.svg",
    category: "Cloud",
    emailPatterns: ["@railway.app"],
  },
  {
    name: "Render",
    slug: "render",
    logoUrl: "https://render.com/favicon.ico",
    category: "Cloud",
    emailPatterns: ["@render.com"],
  },
  {
    name: "DigitalOcean",
    slug: "digitalocean",
    logoUrl: "https://www.digitalocean.com/favicon.ico",
    category: "Cloud",
    emailPatterns: ["@digitalocean.com"],
  },
  {
    name: "Fly.io",
    slug: "fly-io",
    logoUrl: "https://fly.io/favicon.ico",
    category: "Cloud",
    emailPatterns: ["@fly.io"],
  },
  {
    name: "Netlify",
    slug: "netlify",
    logoUrl: "https://www.netlify.com/favicon.ico",
    category: "Cloud",
    emailPatterns: ["@netlify.com"],
  },
  {
    name: "Heroku",
    slug: "heroku",
    logoUrl: "https://www.heroku.com/favicon.ico",
    category: "Cloud",
    emailPatterns: ["@heroku.com", "@salesforce.com"],
  },
  {
    name: "Cloudflare",
    slug: "cloudflare",
    logoUrl: "https://www.cloudflare.com/favicon.ico",
    category: "Cloud",
    emailPatterns: ["@cloudflare.com"],
  },
  {
    name: "Linode",
    slug: "linode",
    logoUrl: "https://www.linode.com/favicon.ico",
    category: "Cloud",
    emailPatterns: ["@linode.com", "@akamai.com"],
  },

  // DevOps & CI/CD
  {
    name: "GitHub",
    slug: "github",
    logoUrl: "https://github.githubassets.com/favicons/favicon.svg",
    category: "CI/CD",
    emailPatterns: ["@github.com"],
  },
  {
    name: "GitLab",
    slug: "gitlab",
    logoUrl: "https://about.gitlab.com/ico/favicon.ico",
    category: "CI/CD",
    emailPatterns: ["@gitlab.com"],
  },
  {
    name: "Atlassian",
    slug: "atlassian",
    logoUrl: "https://www.atlassian.com/favicon.ico",
    category: "CI/CD",
    emailPatterns: ["@atlassian.com"],
  },
  {
    name: "CircleCI",
    slug: "circleci",
    logoUrl: "https://circleci.com/favicon.ico",
    category: "CI/CD",
    emailPatterns: ["@circleci.com"],
  },
  {
    name: "Buildkite",
    slug: "buildkite",
    logoUrl: "https://buildkite.com/favicon.ico",
    category: "CI/CD",
    emailPatterns: ["@buildkite.com"],
  },

  // Monitoring & Observability
  {
    name: "Datadog",
    slug: "datadog",
    logoUrl: "https://www.datadoghq.com/favicon.ico",
    category: "Monitoring",
    emailPatterns: ["@datadoghq.com", "@datadog.com"],
  },
  {
    name: "Sentry",
    slug: "sentry",
    logoUrl: "https://sentry.io/favicon.ico",
    category: "Monitoring",
    emailPatterns: ["@sentry.io", "@getsentry.com"],
  },
  {
    name: "New Relic",
    slug: "new-relic",
    logoUrl: "https://newrelic.com/favicon.ico",
    category: "Monitoring",
    emailPatterns: ["@newrelic.com"],
  },
  {
    name: "PagerDuty",
    slug: "pagerduty",
    logoUrl: "https://www.pagerduty.com/favicon.ico",
    category: "Monitoring",
    emailPatterns: ["@pagerduty.com"],
  },
  {
    name: "Honeycomb",
    slug: "honeycomb",
    logoUrl: "https://www.honeycomb.io/favicon.ico",
    category: "Monitoring",
    emailPatterns: ["@honeycomb.io"],
  },
  {
    name: "LogRocket",
    slug: "logrocket",
    logoUrl: "https://logrocket.com/favicon.ico",
    category: "Monitoring",
    emailPatterns: ["@logrocket.com"],
  },
  {
    name: "Grafana",
    slug: "grafana",
    logoUrl: "https://grafana.com/favicon.ico",
    category: "Monitoring",
    emailPatterns: ["@grafana.com"],
  },
  {
    name: "Better Stack",
    slug: "betterstack",
    logoUrl: "https://betterstack.com/favicon.ico",
    category: "Monitoring",
    emailPatterns: ["@betterstack.com"],
  },

  // AI & Machine Learning
  {
    name: "OpenAI",
    slug: "openai",
    logoUrl: "https://openai.com/favicon.ico",
    category: "AI/ML",
    emailPatterns: ["@openai.com"],
  },
  {
    name: "Anthropic",
    slug: "anthropic",
    logoUrl: "https://www.anthropic.com/favicon.ico",
    category: "AI/ML",
    emailPatterns: ["@anthropic.com", "@mail.anthropic.com"],
  },
  {
    name: "Replicate",
    slug: "replicate",
    logoUrl: "https://replicate.com/favicon.ico",
    category: "AI/ML",
    emailPatterns: ["@replicate.com"],
  },
  {
    name: "Hugging Face",
    slug: "huggingface",
    logoUrl: "https://huggingface.co/favicon.ico",
    category: "AI/ML",
    emailPatterns: ["@huggingface.co"],
  },
  {
    name: "Pinecone",
    slug: "pinecone",
    logoUrl: "https://www.pinecone.io/favicon.ico",
    category: "AI/ML",
    emailPatterns: ["@pinecone.io"],
  },
  {
    name: "Cohere",
    slug: "cohere",
    logoUrl: "https://cohere.ai/favicon.ico",
    category: "AI/ML",
    emailPatterns: ["@cohere.ai", "@cohere.com"],
  },
  {
    name: "ElevenLabs",
    slug: "elevenlabs",
    logoUrl: "https://elevenlabs.io/favicon.ico",
    category: "AI/ML",
    emailPatterns: ["@elevenlabs.io"],
  },
  {
    name: "Together AI",
    slug: "together",
    logoUrl: "https://together.ai/favicon.ico",
    category: "AI/ML",
    emailPatterns: ["@together.ai"],
  },
  {
    name: "Groq",
    slug: "groq",
    logoUrl: "https://groq.com/favicon.ico",
    category: "AI/ML",
    emailPatterns: ["@groq.com"],
  },

  // Databases & Storage
  {
    name: "Supabase",
    slug: "supabase",
    logoUrl: "https://supabase.com/favicon.ico",
    category: "Databases",
    emailPatterns: ["@supabase.io", "@supabase.com"],
  },
  {
    name: "PlanetScale",
    slug: "planetscale",
    logoUrl: "https://planetscale.com/favicon.ico",
    category: "Databases",
    emailPatterns: ["@planetscale.com"],
  },
  {
    name: "MongoDB Atlas",
    slug: "mongodb-atlas",
    logoUrl: "https://www.mongodb.com/favicon.ico",
    category: "Databases",
    emailPatterns: ["@mongodb.com"],
  },
  {
    name: "Redis Cloud",
    slug: "redis-cloud",
    logoUrl: "https://redis.com/favicon.ico",
    category: "Databases",
    emailPatterns: ["@redis.com", "@redislabs.com"],
  },
  {
    name: "Neon",
    slug: "neon",
    logoUrl: "https://neon.tech/favicon.ico",
    category: "Databases",
    emailPatterns: ["@neon.tech"],
  },
  {
    name: "Upstash",
    slug: "upstash",
    logoUrl: "https://upstash.com/favicon.ico",
    category: "Databases",
    emailPatterns: ["@upstash.com"],
  },
  {
    name: "Turso",
    slug: "turso",
    logoUrl: "https://turso.tech/favicon.ico",
    category: "Databases",
    emailPatterns: ["@turso.tech"],
  },
  {
    name: "Algolia",
    slug: "algolia",
    logoUrl: "https://algolia.com/favicon.ico",
    category: "Databases",
    emailPatterns: ["@algolia.com"],
  },

  // Auth & Identity
  {
    name: "Auth0",
    slug: "auth0",
    logoUrl: "https://auth0.com/favicon.ico",
    category: "Auth/Infra",
    emailPatterns: ["@auth0.com"],
  },
  {
    name: "Clerk",
    slug: "clerk",
    logoUrl: "https://clerk.com/favicon.ico",
    category: "Auth/Infra",
    emailPatterns: ["@clerk.dev", "@clerk.com"],
  },
  {
    name: "Okta",
    slug: "okta",
    logoUrl: "https://okta.com/favicon.ico",
    category: "Auth/Infra",
    emailPatterns: ["@okta.com"],
  },
  {
    name: "WorkOS",
    slug: "workos",
    logoUrl: "https://workos.com/favicon.ico",
    category: "Auth/Infra",
    emailPatterns: ["@workos.com"],
  },

  // Payments (using Auth/Infra category)
  {
    name: "Stripe",
    slug: "stripe",
    logoUrl: "https://stripe.com/favicon.ico",
    category: "Auth/Infra",
    emailPatterns: ["@stripe.com"],
  },
  {
    name: "Paddle",
    slug: "paddle",
    logoUrl: "https://paddle.com/favicon.ico",
    category: "Auth/Infra",
    emailPatterns: ["@paddle.com"],
  },
  {
    name: "Lemon Squeezy",
    slug: "lemonsqueezy",
    logoUrl: "https://lemonsqueezy.com/favicon.ico",
    category: "Auth/Infra",
    emailPatterns: ["@lemonsqueezy.com"],
  },

  // Communication
  {
    name: "Twilio",
    slug: "twilio",
    logoUrl: "https://www.twilio.com/favicon.ico",
    category: "Communication",
    emailPatterns: ["@twilio.com"],
  },
  {
    name: "SendGrid",
    slug: "sendgrid",
    logoUrl: "https://sendgrid.com/favicon.ico",
    category: "Communication",
    emailPatterns: ["@sendgrid.com"],
  },
  {
    name: "Resend",
    slug: "resend",
    logoUrl: "https://resend.com/favicon.ico",
    category: "Communication",
    emailPatterns: ["@resend.com"],
  },
  {
    name: "Postmark",
    slug: "postmark",
    logoUrl: "https://postmarkapp.com/favicon.ico",
    category: "Communication",
    emailPatterns: ["@postmarkapp.com"],
  },
  {
    name: "Intercom",
    slug: "intercom",
    logoUrl: "https://intercom.com/favicon.ico",
    category: "Communication",
    emailPatterns: ["@intercom.com", "@intercom.io"],
  },

  // Productivity
  {
    name: "Slack",
    slug: "slack",
    logoUrl: "https://slack.com/favicon.ico",
    category: "Productivity",
    emailPatterns: ["@slack.com"],
  },
  {
    name: "Notion",
    slug: "notion",
    logoUrl: "https://www.notion.so/favicon.ico",
    category: "Productivity",
    emailPatterns: ["@notion.so", "@makenotion.com"],
  },
  {
    name: "Linear",
    slug: "linear",
    logoUrl: "https://linear.app/favicon.ico",
    category: "Productivity",
    emailPatterns: ["@linear.app"],
  },
  {
    name: "Figma",
    slug: "figma",
    logoUrl: "https://www.figma.com/favicon.ico",
    category: "Design",
    emailPatterns: ["@figma.com"],
  },
  {
    name: "Miro",
    slug: "miro",
    logoUrl: "https://miro.com/favicon.ico",
    category: "Productivity",
    emailPatterns: ["@miro.com"],
  },
  {
    name: "Airtable",
    slug: "airtable",
    logoUrl: "https://airtable.com/favicon.ico",
    category: "Productivity",
    emailPatterns: ["@airtable.com"],
  },
  {
    name: "Loom",
    slug: "loom",
    logoUrl: "https://www.loom.com/favicon.ico",
    category: "Productivity",
    emailPatterns: ["@loom.com"],
  },
  {
    name: "Zoom",
    slug: "zoom",
    logoUrl: "https://zoom.us/favicon.ico",
    category: "Productivity",
    emailPatterns: ["@zoom.us"],
  },
  {
    name: "Calendly",
    slug: "calendly",
    logoUrl: "https://calendly.com/favicon.ico",
    category: "Productivity",
    emailPatterns: ["@calendly.com"],
  },
  {
    name: "Asana",
    slug: "asana",
    logoUrl: "https://asana.com/favicon.ico",
    category: "Productivity",
    emailPatterns: ["@asana.com"],
  },
  {
    name: "ClickUp",
    slug: "clickup",
    logoUrl: "https://clickup.com/favicon.ico",
    category: "Productivity",
    emailPatterns: ["@clickup.com"],
  },

  // Dev Tools
  {
    name: "Factory",
    slug: "factory",
    logoUrl: "https://factory.ai/favicon.ico",
    category: "Dev Tools",
    emailPatterns: ["@factory.ai"],
  },
  {
    name: "JetBrains",
    slug: "jetbrains",
    logoUrl: "https://www.jetbrains.com/favicon.ico",
    category: "Dev Tools",
    emailPatterns: ["@jetbrains.com"],
  },
  {
    name: "Postman",
    slug: "postman",
    logoUrl: "https://www.postman.com/favicon.ico",
    category: "Dev Tools",
    emailPatterns: ["@postman.com"],
  },
  {
    name: "ngrok",
    slug: "ngrok",
    logoUrl: "https://ngrok.com/favicon.ico",
    category: "Dev Tools",
    emailPatterns: ["@ngrok.com"],
  },
  {
    name: "Replit",
    slug: "replit",
    logoUrl: "https://replit.com/favicon.ico",
    category: "Dev Tools",
    emailPatterns: ["@replit.com"],
  },
  {
    name: "Gitpod",
    slug: "gitpod",
    logoUrl: "https://gitpod.io/favicon.ico",
    category: "Dev Tools",
    emailPatterns: ["@gitpod.io"],
  },
  {
    name: "Tailscale",
    slug: "tailscale",
    logoUrl: "https://tailscale.com/favicon.ico",
    category: "Dev Tools",
    emailPatterns: ["@tailscale.com"],
  },
  {
    name: "1Password",
    slug: "1password",
    logoUrl: "https://1password.com/favicon.ico",
    category: "Dev Tools",
    emailPatterns: ["@1password.com"],
  },
  {
    name: "Snyk",
    slug: "snyk",
    logoUrl: "https://snyk.io/favicon.ico",
    category: "Dev Tools",
    emailPatterns: ["@snyk.io"],
  },
  {
    name: "LaunchDarkly",
    slug: "launchdarkly",
    logoUrl: "https://launchdarkly.com/favicon.ico",
    category: "Dev Tools",
    emailPatterns: ["@launchdarkly.com"],
  },
  {
    name: "Doppler",
    slug: "doppler",
    logoUrl: "https://doppler.com/favicon.ico",
    category: "Dev Tools",
    emailPatterns: ["@doppler.com"],
  },

  // Analytics
  {
    name: "Mixpanel",
    slug: "mixpanel",
    logoUrl: "https://mixpanel.com/favicon.ico",
    category: "Analytics",
    emailPatterns: ["@mixpanel.com"],
  },
  {
    name: "Amplitude",
    slug: "amplitude",
    logoUrl: "https://amplitude.com/favicon.ico",
    category: "Analytics",
    emailPatterns: ["@amplitude.com"],
  },
  {
    name: "Segment",
    slug: "segment",
    logoUrl: "https://segment.com/favicon.ico",
    category: "Analytics",
    emailPatterns: ["@segment.com"],
  },
  {
    name: "PostHog",
    slug: "posthog",
    logoUrl: "https://posthog.com/favicon.ico",
    category: "Analytics",
    emailPatterns: ["@posthog.com"],
  },
  {
    name: "FullStory",
    slug: "fullstory",
    logoUrl: "https://fullstory.com/favicon.ico",
    category: "Analytics",
    emailPatterns: ["@fullstory.com"],
  },
  {
    name: "Hotjar",
    slug: "hotjar",
    logoUrl: "https://hotjar.com/favicon.ico",
    category: "Analytics",
    emailPatterns: ["@hotjar.com"],
  },

  // Domains (using Other category)
  {
    name: "Namecheap",
    slug: "namecheap",
    logoUrl: "https://namecheap.com/favicon.ico",
    category: "Other",
    emailPatterns: ["@namecheap.com"],
  },
  {
    name: "GoDaddy",
    slug: "godaddy",
    logoUrl: "https://godaddy.com/favicon.ico",
    category: "Other",
    emailPatterns: ["@godaddy.com"],
  },
  {
    name: "Porkbun",
    slug: "porkbun",
    logoUrl: "https://porkbun.com/favicon.ico",
    category: "Other",
    emailPatterns: ["@porkbun.com"],
  },

  // Sales & Marketing
  {
    name: "Apollo",
    slug: "apollo",
    logoUrl: "https://www.apollo.io/favicon.ico",
    category: "Analytics",
    emailPatterns: ["@apollo.io"],
  },
  {
    name: "Genspark",
    slug: "genspark",
    logoUrl: "https://genspark.ai/favicon.ico",
    category: "AI/ML",
    emailPatterns: ["@genspark.ai"],
  },
  {
    name: "Cursor",
    slug: "cursor",
    logoUrl: "https://cursor.sh/favicon.ico",
    category: "Dev Tools",
    emailPatterns: ["@cursor.sh", "@cursor.com"],
  },
  {
    name: "xAI",
    slug: "xai",
    logoUrl: "https://x.ai/favicon.ico",
    category: "AI/ML",
    emailPatterns: ["@x.ai", "@xai.com"],
  },
  {
    name: "Smartlead",
    slug: "smartlead",
    logoUrl: "https://smartlead.ai/favicon.ico",
    category: "Analytics",
    emailPatterns: ["@smartlead.ai"],
  },
  {
    name: "Every",
    slug: "every",
    logoUrl: "https://every.to/favicon.ico",
    category: "Productivity",
    emailPatterns: ["@every.to", "@every.com"],
  },
];
